import { DialogueChunk, CharacterConfigs, ProjectSettings, VoiceSettings } from '../types';

interface ElevenLabsPayload {
  index: number;
  character: string;
  text: string;
  voice_id: string;
  model_id: string;
  voice_settings: VoiceSettings & { use_speaker_boost: boolean };
  output_format: string;
}

interface GeneratedOutput {
  jsonPayload: ElevenLabsPayload[];
  bashScript: string;
}

const OUTPUT_FORMAT_DETAILS: Record<string, { extension: string; accept: string }> = {
  mp3_44100_128: { extension: 'mp3', accept: 'audio/mpeg' },
  mp3_44100_192: { extension: 'mp3', accept: 'audio/mpeg' },
  pcm_24000: { extension: 'wav', accept: 'audio/wav' }
};

const getOutputFormatDetails = (format: string) => OUTPUT_FORMAT_DETAILS[format] || OUTPUT_FORMAT_DETAILS.mp3_44100_128;
// Sequence to safely embed a single quote inside a single-quoted bash string.
const SINGLE_QUOTE_ESCAPE = `'"'"'`;
const escapeSingleQuotes = (value: string) => value.replace(/'/g, SINGLE_QUOTE_ESCAPE);

export const generateElevenLabsScript = (
  dialogueChunks: DialogueChunk[],
  characterConfigs: CharacterConfigs,
  projectSettings: ProjectSettings,
  apiKey: string
): GeneratedOutput => {
  const jsonPayload = dialogueChunks.map((chunk, index): ElevenLabsPayload | null => {
    const config = characterConfigs[chunk.character];

    if (!config || !config.voiceId) {
      return null;
    }

    return {
      index,
      character: chunk.character,
      text: chunk.text,
      voice_id: config.voiceId,
      model_id: projectSettings.model,
      voice_settings: {
        ...config.voiceSettings,
        style: config.voiceSettings.style || 0,
        speed: config.voiceSettings.speed ?? 1,
        use_speaker_boost: true
      },
      output_format: projectSettings.outputFormat
    };
  }).filter((item): item is ElevenLabsPayload => Boolean(item));

  // Generate bash script
  const bashScript = generateBashScript(jsonPayload, apiKey, projectSettings.concatenate, projectSettings.outputFormat);

  return { jsonPayload, bashScript };
};

const generateBashScript = (payload: ElevenLabsPayload[], apiKey: string, concatenate: boolean, outputFormat: string): string => {
  const formatDetails = getOutputFormatDetails(outputFormat);
  let script = `#!/bin/bash

# ElevenLabs Text-to-Speech Generation Script
# Generated by ElevenLabs Screenplay Formatter

set -e  # Exit on error

API_KEY="${apiKey}"
OUTPUT_DIR="./audio_output"

# Create output directory
mkdir -p "$OUTPUT_DIR"

echo "Starting audio generation..."
echo "Total dialogue chunks: ${payload.length}"
echo ""

`;

  // Generate curl commands for each dialogue chunk
  payload.forEach((item) => {
    const filename = `${String(item.index).padStart(4, '0')}_${item.character.replace(/\s+/g, '_')}.${formatDetails.extension}`;
    const payloadJson = JSON.stringify({
      text: item.text,
      model_id: item.model_id,
      voice_settings: item.voice_settings,
      output_format: item.output_format
    });

    script += `# Chunk ${item.index}: ${item.character}\n`;
    script += `echo "Generating: ${item.character} (${item.index + 1}/${payload.length})..."\n`;
    script += `curl -X POST "https://api.elevenlabs.io/v1/text-to-speech/${item.voice_id}" \\\n`;
    script += `  -H "Accept: ${formatDetails.accept}" \\\n`;
    script += `  -H "Content-Type: application/json" \\\n`;
    script += `  -H "xi-api-key: $API_KEY" \\\n`;
    script += `  -d '${escapeSingleQuotes(payloadJson)}' \\\n`;
    script += `  --output "$OUTPUT_DIR/${filename}"\n\n`;

    script += `if [ $? -eq 0 ]; then\n`;
    script += `  echo "✓ Successfully generated ${filename}"\n`;
    script += `else\n`;
    script += `  echo "✗ Failed to generate ${filename}"\n`;
    script += `  exit 1\n`;
    script += `fi\n\n`;
  });

  if (concatenate && payload.length > 1) {
    script += `echo ""\n`;
    script += `echo "Concatenating audio files..."\n\n`;
    script += `# Check if ffmpeg is installed\n`;
    script += `if ! command -v ffmpeg &> /dev/null; then\n`;
    script += `  echo "Warning: ffmpeg is not installed. Skipping concatenation."\n`;
    script += `  echo "Install ffmpeg to enable audio concatenation."\n`;
    script += `else\n`;
    script += `  # Create file list for ffmpeg\n`;
    script += `  FILELIST="$OUTPUT_DIR/filelist.txt"\n`;
    script += `  rm -f "$FILELIST"\n`;
    script += `  for file in "$OUTPUT_DIR"/*.mp3; do\n`;
    script += `    echo "file '$file'" >> "$FILELIST"\n`;
    script += `  done\n\n`;
    script += `  # Concatenate using ffmpeg\n`;
    script += `  ffmpeg -f concat -safe 0 -i "$FILELIST" -c copy "$OUTPUT_DIR/final_output.mp3" -y\n\n`;
    script += `  if [ $? -eq 0 ]; then\n`;
    script += `    echo "✓ Audio files concatenated successfully: $OUTPUT_DIR/final_output.mp3"\n`;
    script += `    rm "$FILELIST"\n`;
    script += `  else\n`;
    script += `    echo "✗ Failed to concatenate audio files"\n`;
    script += `  fi\n`;
    script += `fi\n\n`;
  }

  script += `echo ""\n`;
  script += `echo "Audio generation complete!"\n`;
  script += `echo "Output directory: $OUTPUT_DIR"\n`;
  script += `echo "Total files generated: ${payload.length}"\n`;

  return script;
};

export const validateConfiguration = (
  dialogueChunks: DialogueChunk[],
  characterConfigs: CharacterConfigs,
  apiKey: string
): { valid: boolean; errors: string[] } => {
  const errors: string[] = [];

  if (!apiKey || apiKey.trim() === '') {
    errors.push('API key is required');
  }

  if (dialogueChunks.length === 0) {
    errors.push('No dialogue chunks found in script');
  }

  // Check if all characters have voice IDs configured
  const charactersInDialogue = new Set(dialogueChunks.map(chunk => chunk.character));
  const missingVoiceIds: string[] = [];

  charactersInDialogue.forEach(character => {
    const config = characterConfigs[character];
    if (!config || !config.voiceId || config.voiceId.trim() === '') {
      missingVoiceIds.push(character);
    }
  });

  if (missingVoiceIds.length > 0) {
    errors.push(`Missing voice IDs for characters: ${missingVoiceIds.join(', ')}`);
  }

  return {
    valid: errors.length === 0,
    errors
  };
};
